In [60]:
import os
import pickle
import numpy as np
import supervisedllm

from supervisedllm import data_path
from supervisedllm.data.dataloaders import TopicDataLoader
from supervisedllm.models.baseline_models import NonSequentialRegression

In [66]:
np.single

numpy.float32

In [6]:
data_path

WindowsPath('C:/Users/cesar/Desktop/Projects/supervised-dynamic-llm/data')

In [40]:
data_file = os.path.join(data_path,"preprocessed","arxiv","test.pkl")

In [44]:
data_file

'C:\\Users\\cesar\\Desktop\\Projects\\supervised-dynamic-llm\\data\\preprocessed\\arxiv\\test.pkl'

In [49]:
data_ = pickle.load(open(data_file,"rb"))

In [55]:
len(data_["time"])

434

In [39]:
os.listdir(data_file)

['data',
 'prediction.pkl',
 'test.pkl',
 'time.pkl',
 'train.pkl',
 'validation.pkl',
 'vocabulary.pkl']

In [59]:
data_dir = data_path / "preprocessed" / "wallstreetsbets-score-weekly-medium"
dataloader_params = {"root_dir": data_dir, "batch_size": 32, "is_dynamic":True}
data_loader = TopicDataLoader("cpu", **dataloader_params)

AttributeError: module 'numpy' has no attribute 'float'

In [57]:
databatch = next(data_loader.train.__iter__())

In [58]:
databatch.keys()

dict_keys(['text', 'seq', 'seq_len', 'bow', 'reward', 'reward_bin'])

In [13]:
databatch["bow"]

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [14]:
databatch["text"]

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       dtype=torch.float64)

In [17]:
databatch["seq"]

tensor([[ 1378,  3351,   220,  ..., 10157, 10157, 10157],
        [ 1433,  1959,  9199,  ..., 10157, 10157, 10157],
        [ 1768,   795,  1839,  ..., 10157, 10157, 10157],
        ...,
        [  722,   487,  5875,  ..., 10157, 10157, 10157],
        [ 1354,  4818,   672,  ..., 10157, 10157, 10157],
        [  630,  1415,  1521,  ..., 10157, 10157, 10157]], dtype=torch.int32)

In [20]:
databatch["reward"]

tensor([0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0.],
       dtype=torch.float64)

In [ ]:
# MODEL

In [22]:
model_parameters = NonSequentialRegression.get_parameters(data_loader)
model = NonSequentialRegression(**model_parameters)

In [23]:
model_parameters

{'vocabulary_dim': 2000,
 'dropout': 0.1,
 'output_layers_dim': [10, 10],
 'bow_layers_dim': [10, 10],
 'cov_layers_dim': [10, 10],
 'bow_emb_dim': 50,
 'cov_emb_dim': 50,
 'output_dim': 1,
 'output_transformation': 'relu',
 'word_emb_type': 'bow',
 'covariates_dim': 0,
 'regression_dist': 'exp'}